#!/bin/bash

PERSON1=shiva
PERSON2=Kumar


echo "$PERSON1: Hi $PERSON2"
echo "$PERSON2: Hello $PERSON1"
echo "$PERSON1: How are you are you fine"
echo "$PERSON2: iam fine you are smart"
echo "$PERSON1: Thank you"